{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Exception"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Exception is abnormal condition that arises in a code sequence at run time.\n",
    "* Exception is run time error.\n",
    "* Java exception is an object that describes exceptional (error) condition occurred in piece of code. When such error happen the object representing such error is created and thrown in the method. Method can handle it or pass it on. At some point exception is caught and processed.\n",
    "* `try`, `catch`, `throw`, `throws`, `finally`\n",
    "* Program statement that you want to monitor put in try, If exception occurred in try block it will be thrown, using catch block we can catch such exception and handle it. To manually throw an exception we can use throw keyword.throws clause specify exception that is thrown out of a method. Any code that should be executed after a try block should put in a finally block.\n",
    "\n",
    "```\n",
    "try {\n",
    "    // statements\n",
    "}\n",
    "\n",
    "catch (ExceptionType1 ob) {\n",
    "    // statements\n",
    "}\n",
    "\n",
    "catch (ExceptionType2 ob) {\n",
    "    // statements\n",
    "}\n",
    "\n",
    "finally {\n",
    "    // statements\n",
    "}\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exception types\n",
    "* All exception types are subclass of built-in class `Throwable`. Throwable has immediate 2 subclasses. \n",
    "    - `Exception` : Used for exceptional condition which user program should catch, also we have to subclass this class to create own exception type. There is a subclass of `Exception` which is `RunTimeException`. Which has divide by 0 and invalid array indexing exception.\n",
    "    - `Error`: Exception which should not be caught by program in normal situation. Used by java run time system to indicate error having to do with runtime environment. Ex. Stack overflow\n",
    "    \n",
    "![Exception](images/exception.JPG)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* When Exception is Not handled, then it will be handled by default handler. It prints string describing exception. print stack trace and terminates the program.\n",
    "\n",
    "```\n",
    "int a = 0, b = 0, c = 0;\n",
    "Random r = new Random();\n",
    "\t\t\n",
    "try {\n",
    "\tb = r.nextInt();\n",
    "\tc = r.nextInt();\n",
    "\ta = 12345 / (b/c);\n",
    "\tint d[] = {1};\n",
    "\td[42] = 99;\n",
    "} catch (ArithmeticException e) {\n",
    "\tSystem.out.println(\"Divide by 0\");\n",
    "\t// Throwable overrides the toString() method of Object class.\n",
    "\tSystem.out.println(\"Exception: \" + e); \n",
    "\ta = 0;\n",
    "} catch (ArrayIndexOutOfBoundsException e) {\n",
    "\tSystem.out.println(\"Array index not correct\");\n",
    "}\n",
    "System.out.println(a);\n",
    "```\n",
    "\n",
    "* Exception subclass must come before the superclass, otherwise superclass will eat all the exception and code unreachable error will occur."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Nested try\n",
    "* try inside the block of another try.\n",
    "* Each time try statement is entered context of that exception is pushed onto the stack. If inner try statement does not have catch for particular exception, stack is unwounded and next try statement's catch are inspected.\n",
    "* When method call is involved in try block, and that method also has the try statement then that is the candidate for nested try.\n",
    "\n",
    "\n",
    "### throw\n",
    "\n",
    "```\n",
    "throw ThrowableInstance;\n",
    "```\n",
    "* ThrowableInstance must be object of type `Throwable` or subclass of it. Using parameter in catch or creating with new operator we can get such instance.\n",
    "\n",
    "```\n",
    "public class ExceptionClass {\n",
    "\tstatic void demoproc() {\n",
    "\t\ttry {\n",
    "\t\t\tthrow new NullPointerException(\"demo\");\n",
    "\t\t} catch (NullPointerException e) {\n",
    "\t\t\tSystem.out.println(\"Got it\");\n",
    "\t\t\tthrow e; // rethrow the exception\n",
    "\t\t}\n",
    "\t}\n",
    "\t\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\ttry {\n",
    "\t\t\tdemoproc();\n",
    "\t\t} catch (NullPointerException e) {\n",
    "\t\t\tSystem.out.println(\"Recaught: \" + e);\n",
    "\t\t}\n",
    "\t}\n",
    "}\n",
    "\n",
    "```\n",
    "* Throwable exception has 2 types of constructor. First with no arguments, other with 1 String argument. String argument describes exception. That string will displayed when exception object is printed or calling `getMessage()`."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### throws\n",
    "* If method causes exception that it does not handle, it must specify such behavior so that callers of the method can guard  themselves against that exception. Using `throws` in method's declaration we can achieve this. throws list type of exceptions that method can trigger.\n",
    "* Not mentioning throws can create compile \n",
    "\n",
    "```\n",
    "type methodName(para-list) throws exception-list //comma separated list\n",
    "{\n",
    "    // body\n",
    "}\n",
    "\n",
    "void throwOne() throws IllegalAccessException {\n",
    "    throw new IllegalAccessException\n",
    "}\n",
    "```\n",
    "\n",
    "### finally\n",
    "* It creates a block which will be executed after try/catch. It will executes whether or not exception is thrown. Useful for closing file or release resources.\n",
    "\n",
    "```\n",
    "public class FinallyDemo {\n",
    "\tstatic void a() {\n",
    "\t\ttry {\n",
    "\t\t\tSystem.out.println(\"Inside A\");\n",
    "\t\t\tthrow new RuntimeException();\n",
    "\t\t} finally {\n",
    "\t\t\tSystem.out.println(\"A's finally\");\n",
    "\t\t}\n",
    "\t}\n",
    "\tstatic void b() {\n",
    "\t\ttry {\n",
    "\t\t\tSystem.out.println(\"Inside B\");\n",
    "\t\t\treturn;\n",
    "\t\t} finally {\n",
    "\t\t\tSystem.out.println(\"B's finally\");\n",
    "\t\t}\n",
    "\t}\n",
    "\tstatic void c() {\n",
    "\t\ttry {\n",
    "\t\t\tSystem.out.println(\"Inside C\");\n",
    "\t\t} finally {\n",
    "\t\t\tSystem.out.println(\"A's finally\");\n",
    "\t\t}\n",
    "\t}\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\ttry {\n",
    "\t\t\ta();\n",
    "\t\t} catch (Exception e) {\n",
    "\t\t\tSystem.out.println(\"caught\");\n",
    "\t\t}\n",
    "\t\tb();\n",
    "\t\tc();\n",
    "\t}\n",
    "}\n",
    "\n",
    "```\n",
    "\n",
    "* Output \n",
    "```\n",
    "Inside A\n",
    "A's finally\n",
    "caught\n",
    "Inside B\n",
    "B's finally\n",
    "Inside C\n",
    "A's finally\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Built-in exception\n",
    "* `java.lang` defines several exception classes.\n",
    "* Exception of subclasses of `EunTImeException` are not needed to include in throws list. Such exception is called **unchecked exception** because compiler does not check whether method handles or throws such exception.\n",
    "* List of unchecked exception\n",
    "![unchecked](images/unchecked.JPG)\n",
    "* Other is **checked exception** which must be included in throws list if method generate it and does not handle.\n",
    "![checked](images/checked.JPG)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Creating own exception subclass\n",
    "* Define a subclass of `Exception`.\n",
    "* `Exception` is subclass of `Throwable`. `Throwable` defines methods, which we can override in our own subclass.\n",
    "* Methods defined by `Throwable`.\n",
    "![throwable](images/throwable.JPG)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```\n",
    "public class MyException extends Exception{\n",
    "\tprivate int detail;\n",
    "\t\n",
    "\tMyException(int a) {\n",
    "\t\tdetail = a;\n",
    "\t}\n",
    "\tpublic String toString() {\n",
    "\t\treturn \"My Exception\" + detail;\n",
    "\t}\n",
    "}\n",
    "\n",
    "\n",
    "public class Demo {\n",
    "\tstatic void compute(int a) throws MyException {\n",
    "\t\tSystem.out.println(\"Compute called\");\n",
    "\t\tif (a > 10)\n",
    "\t\t\tthrow new MyException(a);\n",
    "\t\tSystem.out.println(\"Normal exit\");\n",
    "\t}\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\ttry {\n",
    "\t\t\tcompute(1);\n",
    "\t\t\tcompute(11);\n",
    "\t\t} catch (MyException e){\n",
    "\t\t\tSystem.out.println(\"caught\" + e);\n",
    "\t\t}\n",
    "\t}\n",
    "}\n",
    "\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Chined Exceptions\n",
    "* Allows us to associate another exception with exception.\n",
    "* Second exception describe the cause of first exception.\n",
    "* Method throws `ArithmeticException` because of an attempt to divide by 0. But actual cause is I/O error which set divisor improperly.\n",
    "\n",
    "```\n",
    "Throwable(Throwable causeExc)\n",
    "Throwable(String msg, Throwable causeExc)\n",
    "```\n",
    "* causeExc is exception that cause current exception.\n",
    "* `getCause()` and `initCause(Throwable causeExc)` are defined by `Throwable`.\n",
    "* `getCause()` returns the exception that created current exception. If there no underlying exception null is returned.\n",
    "* `initCause(Throwable causeExc)` method associates causeExc with the invoking exception and returns a reference to the exception. So we can associate cause with exception, after exception is created. We can call `initCause(Throwable causeExc)` only once for each object of exception. `initCause(Throwable causeExc)` is used to set cause for legacy exception class that do not support the two additional constructor described earlier.\n",
    "\n",
    "```\n",
    "public class Demo {\n",
    "\tstatic void demoproc() {\n",
    "\t\tNullPointerException e = new NullPointerException(\"top layer\");\n",
    "\t\t\n",
    "\t\te.initCause(new ArithmeticException(\"cause\"));\n",
    "\t\t\n",
    "\t\tthrow e;\n",
    "\t}\n",
    "\tpublic static void main(String[] args) {\n",
    "\t\ttry {\n",
    "\t\t\tdemoproc();\n",
    "\t\t} catch (NullPointerException e){\n",
    "\t\t\tSystem.out.println(\"caught\" + e);\n",
    "\t\t\tSystem.out.println(\"original cause\" + e.getCause());\n",
    "\t\t}\n",
    "\t}\n",
    "}\n",
    "\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### multi-catch\n",
    "* Added in JDK 7\n",
    "* 2 or more exception caught by the same c.atch. Separate the exception type in catch statement with `|` operator. Each multi-catch parameter is implicitly `final` \n",
    "\n",
    "```\n",
    "catch(ArithmeticException | ArrayOutOfBoundException e)\n",
    "```\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
